+incdir+../common
+incdir+../../sim/common
+incdir+../../rtl
../../sim/common/tb_clk_gen.v
../../sim/common/glbl.v
../../sim/common/BUFG.v
../../sim/common/BUFPLL.v
../../sim/common/IBUFDS.v
../../sim/common/IBUFG.v
../../sim/common/IODELAY2.v
../../sim/common/ISERDES2.v
../../sim/common/OBUFDS.v
../../sim/common/OSERDES2.v
../../sim/common/PLL_ADV.v
../../rtl/ber_7seg.v
../../rtl/blink_7seg.v
../../rtl/button_ctrl.v
../../rtl/cnt10.v
../../rtl/cnt_down.v
../../rtl/dechat.v
../../rtl/div.v
../../rtl/encode_7seg.v
../../rtl/fifo_async.v
../../rtl/handle_7seg.v
../../rtl/lfsr32x2.v
../../rtl/lvds_test.v
../../rtl/mult.v
../../rtl/pll_ctrl.v
../../rtl/pll_drp.v
../../rtl/pseudo_sram.v
../../rtl/pulse_extend.v
../../rtl_cmos/stimulus.v
../../rtl_cmos/seq.v
