+incdir+../common
+incdir+../../rtl
../common/tb_clk_gen.v
../common/PLL_ADV_short.v
../common/glbl.v
../common/IBUFDS.v
../common/IDDR2.v
../common/IODELAY2.v
../common/OBUFDS.v
../common/OBUFT.v
../common/ODDR2.v
../../rtl/blink_7seg.v
../../rtl/dechat.v
../../rtl/fifo_async.v
../../rtl/lvds1.v
../../rtl/parallel_recv.v
../../rtl/parallel_send.v
../../rtl/pll_ctrl.v
../../rtl/pll_drp.v
../../rtl/pll_test.v
../../rtl/pseudo_sram.v
../../rtl/serial_recv.v
../../rtl/serial_send.v
../../rtl/word_align.v
